---
title: "国際政治経済I"
subtitle: "学習院大学｜法学部政治学科｜2026年度第一学期｜月曜日5限"
date: 2026-03-19
date-modified: today
author:
  - name: 鈴木淳平
    affiliation: 学習院大学法学部政治学科
#    email: jsuzuki@komazawa-u.ac.jp
#    url: https://junpei-suzuki.github.io
---

::: callout-important
#### 注意

このページは2026年度の学習院大学法学部政治学科で開講される国際政治経済Iの最新版のシラバスおよび授業資料を兼ねたものです。現時点（2026年3月19日）では未完成であり、内容には不備や誤りが含まれます。今後随時更新していきます。
:::

## 基礎情報
 - 学期：第一学期
 - 日時：月曜日5限 (17:05-18:50)
 - 場所：TBD
 - 担当教員：鈴木淳平
     <!-- - 本務校：駒澤大学法学部政治学科 -->
     <!-- - 連絡先：[jsuzuki@komazawa-u.ac.jp](mailto:jsuzuki@komazawa-u.ac.jp) -->

## 授業概要

グローバル化が進む現代、政治と経済とはますます強く結びついており、両者を分けて考えることはもはや不可能です。この科目では、そうした政治と経済の関わりについて、国際関係論の視点から考察できる能力を身につけることを目的としています。国際政治経済学の研究成果から関連する概念・理論・モデルを学び、越境する経済活動をめぐって繰り広げられる国際政治について、「印象」ではなく「根拠」に基づいて分析できる視座を提供していきます。特に第一学期の「国際政治経済I」では、貿易と金融をめぐる政治を扱います。授業では適宜アクティブラーニングを取り入れ、お互いに学び合いながら知識の習得を深めるとともに、学んだ知識を応用しながら国際政治経済を考察する経験を積めるよう手助けをしていきます。

**キーワード**：国際政治経済、国際関係論、パラダイム、国際秩序、自由貿易、保護主義、国際金融、国際収支、為替、GATT／WTO、ブレトン・ウッズ体制

## 授業計画

| 回  | 日付 | 部・到達目標        | テーマ                             |
|-----|:-----|:--------------------|:-----------------------------------|
| 1   | 4/13  | イントロダクション | [**はじめに**](01_intro.qmd)                       |
| 2   | 4/20  | パラダイムと歴史   | [**国際政治経済学のパラダイム** ](02_paradigm.qmd)    |
| 3   | 4/27  | パラダイムと歴史   | [**主権国家体制**](03_sovereign.qmd)                   |
| 4   | 5/11  | パラダイムと歴史   | [**パックス・ブリタニカと世界大戦**](04_pax_britannica.qmd) |
| 5   | 5/18  | パラダイムと歴史   | **戦後国際秩序**                   |
| 6   | 5/25  | 貿易               | **貿易の経済学**                   |
| 7   | 6/1   | 貿易               | **保護主義の政治学**               |
| 8   | 6/8   | 貿易               | **貿易交渉**                       |
| 9   | 6/15  | 貿易               | **GATT/WTO体制**                   |
| 10  | 6/22  | 国際金融           | **国際収支**                       |
| 11  | 6/29  | 国際金融           | **為替制度**                       |
| 12  | 7/6   | 国際金融　　　     | **マクロ経済政策と国際金融**       |
| 13  | 7/13  | 国際金融　　　     | **ブレトン・ウッズ体制**           |
| 14  | TBD   | まとめ             | **理解度の確認**                   |
